"""Template-based explanation generator.

Every sentence is assembled from fixed templates and real numbers — nothing is
generated by a language model. An explanation only ever claims what the data
supports: if a score came from the cold-start population prior, it never says
"based on your taste".
"""

from __future__ import annotations

import random
import re

# Mood vocabulary -> the genres that vocabulary implies. Used to quote the
# user's own words back to them and to name why a genre matched.
MOOD_LEXICON: dict[str, tuple[str, ...]] = {
    "dark": ("Film-Noir", "Thriller", "Crime", "Horror"),
    "gritty": ("Crime", "Drama", "Thriller"),
    "bleak": ("Drama", "Film-Noir", "War"),
    "mind-blowing": ("Sci-Fi", "Mystery", "Thriller"),
    "mind blowing": ("Sci-Fi", "Mystery", "Thriller"),
    "mind-bending": ("Sci-Fi", "Mystery"),
    "cerebral": ("Sci-Fi", "Drama", "Mystery"),
    "clever": ("Mystery", "Sci-Fi", "Thriller"),
    "twist": ("Thriller", "Mystery"),
    "scary": ("Horror", "Thriller"),
    "creepy": ("Horror", "Mystery"),
    "tense": ("Thriller", "Crime"),
    "suspense": ("Thriller", "Mystery"),
    "funny": ("Comedy",),
    "hilarious": ("Comedy",),
    "laugh": ("Comedy",),
    "light": ("Comedy", "Romance", "Animation"),
    "lighthearted": ("Comedy", "Romance", "Children's"),
    "feel good": ("Comedy", "Romance", "Musical"),
    "feel-good": ("Comedy", "Romance", "Musical"),
    "happy": ("Comedy", "Musical", "Children's"),
    "uplifting": ("Musical", "Comedy", "Drama"),
    "sad": ("Drama",),
    "emotional": ("Drama", "Romance"),
    "moving": ("Drama",),
    "cry": ("Drama", "Romance"),
    "romantic": ("Romance",),
    "love": ("Romance",),
    "epic": ("Adventure", "War", "Fantasy"),
    "action": ("Action",),
    "fast": ("Action", "Thriller"),
    "exciting": ("Action", "Adventure"),
    "adventure": ("Adventure",),
    "magical": ("Fantasy", "Animation"),
    "weird": ("Fantasy", "Sci-Fi"),
    "classic": ("Drama", "Western", "Film-Noir"),
    "true story": ("Documentary", "Drama"),
    "real": ("Documentary",),
    "space": ("Sci-Fi",),
    "future": ("Sci-Fi",),
    "war": ("War",),
    "family": ("Children's", "Animation"),
    "kids": ("Children's", "Animation"),
    "animated": ("Animation",),
    "musical": ("Musical",),
    "mystery": ("Mystery",),
    "thriller": ("Thriller",),
    "horror": ("Horror",),
}

# Descriptive words worth quoting back even when they aren't in the lexicon.
_STOPWORDS = {
    "i", "a", "an", "the", "want", "something", "movie", "film", "watch",
    "me", "my", "to", "for", "and", "but", "not", "too", "with", "that",
    "is", "it", "of", "in", "on", "some", "really", "very", "would", "like",
    "feel", "feeling", "tonight", "please", "give", "show", "need", "am",
    # Filler that reads badly when quoted back: 'you asked for "don't"'.
    "know", "don't", "dont", "sure", "surprise", "whatever", "anything",
    "thing", "things", "stuff", "mood", "today", "night", "week", "weekend",
    "good", "great", "nice", "watching", "recommend", "idea", "maybe",
    "think", "just", "about", "have", "been", "into", "some", "long",
}

_TIME_LABEL = {"~1hr": "about an hour", "~2hrs": "around two hours", "~3hrs+": "a long sitting"}
_COMPANY_PHRASE = {
    "Alone": "a solo watch",
    "Partner": "watching with your partner",
    "Family": "family viewing",
    "Friends": "a night in with friends",
}


def extract_mood_terms(mood_text: str) -> list[str]:
    """Words from the user's own text, lexicon matches first."""
    low = (mood_text or "").lower()
    hits = [phrase for phrase in MOOD_LEXICON if phrase in low]
    hits.sort(key=lambda p: (-len(p), p))          # prefer "mind-blowing" over "dark"

    if not hits:
        words = [w for w in re.findall(r"[a-z'-]{4,}", low) if w not in _STOPWORDS]
        hits = words[:2]

    # Drop a term already contained in a longer one we kept.
    kept: list[str] = []
    for h in hits:
        if not any(h in k and h != k for k in kept):
            kept.append(h)
    return kept[:3]


def implied_genres(mood_terms: list[str]) -> list[str]:
    out: list[str] = []
    for term in mood_terms:
        for g in MOOD_LEXICON.get(term, ()):
            if g not in out:
                out.append(g)
    return out


def _article(word: str) -> str:
    """'a' / 'an' for a genre label — "an Adventure film", not "a Adventure"."""
    return "an" if word[:1].upper() in "AEIOU" else "a"


def _quote(terms: list[str]) -> str:
    if not terms:
        return "what you described"
    quoted = [f'"{t}"' for t in terms]
    if len(quoted) == 1:
        return quoted[0]
    return ", ".join(quoted[:-1]) + f" and {quoted[-1]}"


def build_explanation(
    *,
    title: str,
    genres: list[str],
    release_year: int | None,
    runtime_minutes: int | None,
    mood_text: str,
    mood_terms: list[str],
    ncf_norm: float,
    sbert_norm: float,
    personalised: bool,
    genre_affinity: dict[str, tuple[float, int, int]],
    rating_count: int,
    watching_with: str | None,
    time_available: str | None,
    seed: int,
    model_scored: bool = True,
) -> str:
    """Assemble 2-3 sentences: mood match, then taste evidence, then context."""
    rng = random.Random(seed)
    genre_str = ", ".join(genres[:2]) if genres else "hard-to-classify"
    matched = [g for g in implied_genres(mood_terms) if g in genres]
    parts: list[str] = []

    # --- 1. why it matches the mood ---
    if matched:
        opener = rng.choice(
            [
                f"You asked for {_quote(mood_terms)}, and this {matched[0]} pick leans straight into it.",
                f"This one matches {_quote(mood_terms)} — it's {matched[0]} through and through.",
                f"Because you wanted {_quote(mood_terms)}, {_article(matched[0])} {matched[0]} film like this fits closely.",
            ]
        )
    elif sbert_norm >= 0.6:
        opener = rng.choice(
            [
                f"Its {genre_str} tone reads as a close match for {_quote(mood_terms)}.",
                f"On mood alone this scored highly against {_quote(mood_terms)}.",
            ]
        )
    else:
        opener = (
            f"{_article(genre_str).capitalize()} {genre_str} choice — not the most literal read "
            f"of {_quote(mood_terms)}, but it scored too well on your predicted taste to leave out."
        )
    parts.append(opener)

    # --- 2. what the rating history / model supports ---
    liked = [
        (g, avg, n, real)
        for g, (avg, n, real) in genre_affinity.items()
        if g in genres and n >= 1 and avg >= 3.5
    ]
    # Genres the user has genuinely rated outrank ones they only picked at signup.
    liked.sort(key=lambda x: (-(x[3] > 0), -x[1], -x[2]))

    # A film outside the trained model never gets a sentence implying the
    # collaborative model rated it: the number was borrowed, and saying so is
    # the whole point of labelling estimates.
    if not model_scored:
        if liked:
            g = liked[0][0]
            parts.append(
                f"It is too recent for our ratings model, so this is estimated from "
                f"{g} films it does know — which land at {ncf_norm * 100:.0f}/100 for you."
            )
        else:
            parts.append(
                "It is too recent for our ratings model, so this score is estimated "
                f"from similar films it does know ({ncf_norm * 100:.0f}/100)."
            )
    elif liked:
        g, avg, n, real = liked[0]
        if real > 0:
            film_word = "film" if real == 1 else "films"
            parts.append(f"You've rated {g} {film_word} {avg:.1f} on average ({real} so far), and the model puts this at {ncf_norm * 100:.0f}/100 for you.")
        else:
            # Onboarding seeds only. The genre may be incidental — a seeded film
            # can carry genres the user never picked — so describe the starter
            # picks rather than claiming the user chose this genre.
            parts.append(f"Your starter picks lean {g}, and the model puts this at {ncf_norm * 100:.0f}/100 for you.")
    elif personalised and rating_count > 0:
        parts.append(f"Across your {rating_count} rated {'film' if rating_count == 1 else 'films'}, the model scores this {ncf_norm * 100:.0f}/100.")
    else:
        parts.append(f"You haven't rated much yet, so this comes from what viewers broadly agree on — it scores {ncf_norm * 100:.0f}/100 on that baseline.")

    # --- 3. viewing context, only when there is something real to say ---
    ctx: list[str] = []
    if time_available and runtime_minutes:
        ctx.append(f"At {runtime_minutes} min it fits {_TIME_LABEL.get(time_available, time_available)}")
    if watching_with in _COMPANY_PHRASE:
        ctx.append(("and works for " if ctx else "It suits ") + _COMPANY_PHRASE[watching_with])
    if ctx:
        parts.append(" ".join(ctx).strip() + ".")
    elif release_year:
        parts.append(f"From {release_year}.")

    return " ".join(parts)
